In [22]:
import pandas as pd

data = {
    "DocumentDate": ["02/01/2025"],#
    "DocType": ["unknown"],
    "TransactionType": ["SAP"],
    "BankTrfRef": ["unknown"],
    "Amount": [7800],
    "TransactionRefNo": ["W1dsfsafjdjfb"],
    "MerchantRefNum": ["777741344598"],
    "CR_DR": ["CR"],
    "GLRecordID": ["unknown"],
    "OID": ["unknown"],
    "PONumber": ["13u350u5u05"],
    "CardNo": ["13415555531535"],
    "ReceiptNumber": ["unknown"],
    "AccountingDocNum": ["KD0nfdkk"],
    "AuthCode": ["unknown"],
    "RefDocument": ["unknown"],
    "Assignment": ["unknown"],
    "StoreNumber": ["unknown"],
    "AcquireRefNumber": ["unknown"],
    "WebOrderNumber": ["W1342421414"],
    "MatchGroupId": ["14443553"],
    "Source": ["SAP"],
    "SourceType": ["Internal"],
    "RawClusterId": ["1"]
}

data1 = {
    "DocumentDate": ["02/01/2025"],#
    "DocType": ["unknown"],
    "TransactionType": ["SAP"],
    "BankTrfRef": ["unknown"],
    "Amount": [7800],
    "TransactionRefNo": ["W1dsfsafjdjfb"],
    "MerchantRefNum": ["777741344598"],
    "CR_DR": ["CR"],
    "GLRecordID": ["unknown"],
    "OID": ["unknown"],
    "PONumber": ["13u350u5u05"],
    "CardNo": ["13415555531535"],
    "ReceiptNumber": ["unknown"],
    "AccountingDocNum": ["KD0nfdkk"],
    "AuthCode": ["unknown"],
    "RefDocument": ["unknown"],
    "Assignment": ["unknown"],
    "StoreNumber": ["unknown"],
    "AcquireRefNumber": ["unknown"],
    "WebOrderNumber": ["W1342421414"],
    "MatchGroupId": ["14443553"],
    "Source": ["SAP"],
    "SourceType": ["Internal"],
    "RawClusterId": ["1"]
}

data2 = {
    "DocumentDate": ["02/01/2025"],#
    "DocType": ["unknown"],
    "TransactionType": ["SAP"],
    "BankTrfRef": ["unknown"],
    "Amount": [7800],
    "TransactionRefNo": ["W1dsfsafjdjfb"],
    "MerchantRefNum": ["777741344598"],
    "CR_DR": ["CR"],
    "GLRecordID": ["unknown"],
    "OID": ["unknown"],
    "PONumber": ["13u350u5u05"],
    "CardNo": ["13415555531535"],
    "ReceiptNumber": ["unknown"],
    "AccountingDocNum": ["KD0nfdkk"],
    "AuthCode": ["unknown"],
    "RefDocument": ["unknown"],
    "Assignment": ["unknown"],
    "StoreNumber": ["unknown"],
    "AcquireRefNumber": ["unknown"],
    "WebOrderNumber": ["W1342421414"],
    "MatchGroupId": ["14443554"],
    "Source": ["SAP"],
    "SourceType": ["Internal"],
    "RawClusterId": ["2"]
}
data3 = {
    "DocumentDate": ["02/01/2025"],#
    "DocType": ["unknown"],
    "TransactionType": ["SAP"],
    "BankTrfRef": ["unknown"],
    "Amount": [7800],
    "TransactionRefNo": ["W1dsfsafjdjfb"],
    "MerchantRefNum": ["777741344598"],
    "CR_DR": ["CR"],
    "GLRecordID": ["unknown"],
    "OID": ["unknown"],
    "PONumber": ["13u350u5u05"],
    "CardNo": ["13415555531535"],
    "ReceiptNumber": ["unknown"],
    "AccountingDocNum": ["KD0nfdkk"],
    "AuthCode": ["unknown"],
    "RefDocument": ["unknown"],
    "Assignment": ["unknown"],
    "StoreNumber": ["unknown"],
    "AcquireRefNumber": ["unknown"],
    "WebOrderNumber": ["W1342421414"],
    "MatchGroupId": ["14443554"],
    "Source": ["SAP"],
    "SourceType": ["Internal"],
    "RawClusterId": ["2"]
}
data4 = {
    "DocumentDate": ["02/01/2025"],#
    "DocType": ["unknown"],
    "TransactionType": ["SAP"],
    "BankTrfRef": ["unknown"],
    "Amount": [7800],
    "TransactionRefNo": ["W1dsfsafjdjfb"],
    "MerchantRefNum": ["777741344598"],
    "CR_DR": ["CR"],
    "GLRecordID": ["unknown"],
    "OID": ["unknown"],
    "PONumber": ["13u350u5u05"],
    "CardNo": ["13415555531535"],
    "ReceiptNumber": ["unknown"],
    "AccountingDocNum": ["KD0nfdkk"],
    "AuthCode": ["unknown"],
    "RefDocument": ["unknown"],
    "Assignment": ["unknown"],
    "StoreNumber": ["unknown"],
    "AcquireRefNumber": ["unknown"],
    "WebOrderNumber": ["W1342421414"],
    "MatchGroupId": ["14443555"],
    "Source": ["SAP"],
    "SourceType": ["Internal"],
    "RawClusterId": ["2"]
}
data5 = {
    "DocumentDate": ["02/01/2025"],#
    "DocType": ["unknown"],
    "TransactionType": ["SAP"],
    "BankTrfRef": ["unknown"],
    "Amount": [7800],
    "TransactionRefNo": ["W1dsfsafjdjfb"],
    "MerchantRefNum": ["777741344598"],
    "CR_DR": ["CR"],
    "GLRecordID": ["unknown"],
    "OID": ["unknown"],
    "PONumber": ["13u350u5u05"],
    "CardNo": ["13415555531535"],
    "ReceiptNumber": ["unknown"],
    "AccountingDocNum": ["KD0nfdkk"],
    "AuthCode": ["unknown"],
    "RefDocument": ["unknown"],
    "Assignment": ["unknown"],
    "StoreNumber": ["unknown"],
    "AcquireRefNumber": ["unknown"],
    "WebOrderNumber": ["W1342421414"],
    "MatchGroupId": ["14443555"],
    "Source": ["SAP"],
    "SourceType": ["Internal"],
    "RawClusterId": ["3"]
}
df_lst = []
for each in [data1,data2,data3,data4,data5]:
    df = pd.DataFrame(each)
    df_lst.append(df)
df = pd.concat(df_lst, ignore_index=True)
df

,DocumentDate,DocType,TransactionType,BankTrfRef,Amount,TransactionRefNo,MerchantRefNum,CR_DR,GLRecordID,OID,...,AuthCode,RefDocument,Assignment,StoreNumber,AcquireRefNumber,WebOrderNumber,MatchGroupId,Source,SourceType,RawClusterId
0,02/01/2025,unknown,SAP,unknown,7800,W1dsfsafjdjfb,777741344598,CR,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,W1342421414,14443553,SAP,Internal,1
1,02/01/2025,unknown,SAP,unknown,7800,W1dsfsafjdjfb,777741344598,CR,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,W1342421414,14443554,SAP,Internal,2
2,02/01/2025,unknown,SAP,unknown,7800,W1dsfsafjdjfb,777741344598,CR,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,W1342421414,14443554,SAP,Internal,2
3,02/01/2025,unknown,SAP,unknown,7800,W1dsfsafjdjfb,777741344598,CR,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,W1342421414,14443555,SAP,Internal,2
4,02/01/2025,unknown,SAP,unknown,7800,W1dsfsafjdjfb,777741344598,CR,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,W1342421414,14443555,SAP,Internal,3

How many clusters did your solution find? And how many clusters that it supposed to find as such if we compare to human match groups

In [23]:
df.MatchGroupId.value_counts()

MatchGroupId
14443554    2
14443555    2
14443553    1
Name: count, dtype: int64

In [24]:
df.RawClusterId.value_counts()

RawClusterId
2    3
1    1
3    1
Name: count, dtype: int64

In [25]:
print(f"N clusters found: {df.RawClusterId.nunique()}")
print(f"N clusters supposed to find: {df.MatchGroupId.nunique()}")

N clusters found: 3
N clusters supposed to find: 3

In [26]:
grouped_df = df.groupby('RawClusterId').agg(
    UniqueMatchGroupIds=('MatchGroupId', 'nunique'),
    TotalAmountPerCluster=('Amount', 'sum')
).reset_index()

print(grouped_df.head(2))

  RawClusterId  UniqueMatchGroupIds  TotalAmountPerCluster
0            1                    1                   7800
1            2                    2                  23400

In [27]:
df = pd.merge(df, grouped_df, on='RawClusterId', how='left')
df.head(2)

,DocumentDate,DocType,TransactionType,BankTrfRef,Amount,TransactionRefNo,MerchantRefNum,CR_DR,GLRecordID,OID,...,Assignment,StoreNumber,AcquireRefNumber,WebOrderNumber,MatchGroupId,Source,SourceType,RawClusterId,UniqueMatchGroupIds,TotalAmountPerCluster
0,02/01/2025,unknown,SAP,unknown,7800,W1dsfsafjdjfb,777741344598,CR,unknown,unknown,...,unknown,unknown,unknown,W1342421414,14443553,SAP,Internal,1,1,7800
1,02/01/2025,unknown,SAP,unknown,7800,W1dsfsafjdjfb,777741344598,CR,unknown,unknown,...,unknown,unknown,unknown,W1342421414,14443554,SAP,Internal,2,2,23400

In [28]:
def is_semi_valid_cluster(row):
  if row.UniqueMatchGroupIds == 1 and row.TotalAmountPerCluster == 0:
    return True
  else:
    return False
df['is_semi_valid_cluster'] = df.apply(lambda row: is_semi_valid_cluster(row), axis=1)

In [34]:
print(f"N clusters found: {}, N clusters supposed to find: {df.MatchGroupId.nunique()}")
print(f"N cluster with unique MatchGroupId {df[df['UniqueMatchGroupIds']==1].RawClusterId.nunique()} and not unique MatchGroupIds {df[df['UniqueMatchGroupIds']!=1].RawClusterId.nunique()}")
print(f"With in the ")
print(f"Number of semi valid cluster (Criteria: Single Unique MatchGroupId and Amount adding up to 0): {df[df['is_semi_valid_cluster']==True].RawClusterId.nunique()}")

N clusters found: 3, N clusters supposed to find: 3
N cluster with unique MatchGroupId 2 and not unique MatchGroupIds 1
Number of semi valid cluster (Criteria: Single Unique MatchGroupId and Amount adding up to 0): 0

In [42]:
n_clusters_found = df.RawClusterId.nunique()
n_expected_clusters = df.MatchGroupId.nunique()

n_clusters_with_unique_matchgroupids = df[df['UniqueMatchGroupIds']==1].RawClusterId.nunique()
n_clusters_with_unique_matchgroupids_and_amount_adding_up_to_0 = df[(df['UniqueMatchGroupIds']==1) & (df['TotalAmountPerCluster']==0)].RawClusterId.nunique()
n_clusters_with_unique_matchgroupids_and_amount_NOT_adding_up_to_0 = df[(df['UniqueMatchGroupIds']==1) & (df['TotalAmountPerCluster']!=0)].RawClusterId.nunique()

n_clusters_with_non_unique_matchgroupids = df[df['UniqueMatchGroupIds']!=1].RawClusterId.nunique()
n_clusters_with_non_unique_matchgroupids_and_amount_adding_up_to_0 = df[(df['UniqueMatchGroupIds']!=1) & (df['TotalAmountPerCluster']==0)].RawClusterId.nunique()
n_clusters_with_non_unique_matchgroupids_and_amount_NOT_adding_up_to_0 = df[(df['UniqueMatchGroupIds']!=1) & (df['TotalAmountPerCluster']!=0)].RawClusterId.nunique()

semi_valid_clusters_stats = {"Amount_Added_to_0": [n_clusters_with_unique_matchgroupids_and_amount_adding_up_to_0, n_clusters_with_non_unique_matchgroupids_and_amount_adding_up_to_0],
                             "Amount_Not_Added_to_0": [n_clusters_with_unique_matchgroupids_and_amount_NOT_adding_up_to_0, n_clusters_with_non_unique_matchgroupids_and_amount_NOT_adding_up_to_0]}


semi_valid_clusters_stats_df = pd.DataFrame(semi_valid_clusters_stats)
semi_valid_clusters_stats_df.index = ["Clusters_with_Unique_MatchGroupId", "Clusters_with_Non_Unique_MatchGroupId"]
print("Note that cell (0,0) is the semi-valid cluster (i.e) Clusters with Unique MatchGroupId and Amount adding up to 0")
semi_valid_clusters_stats_df

Note that cell (0,0) is the semi-valid cluster (i.e) Clusters with Unique MatchGroupId and Amount adding up to 0

,Amount_Added_to_0,Amount_Not_Added_to_0
Clusters_with_Unique_MatchGroupId,0,2
Clusters_with_Non_Unique_MatchGroupId,0,1

# Task
Install the `scikit-learn` library, define a Python function `perform_train_test_split(df, train_test_ratio=0.7)` that splits the input DataFrame `df` into training and testing sets while preserving the distribution of `MatchGroupId` sizes, apply this function with a `train_test_ratio` of 0.7 to create `train_df` and `test_df`, print the shapes of these resulting DataFrames, and then calculate and display the distribution of `MatchGroupId` sizes for `df`, `train_df`, and `test_df` to verify the stratification.

## Install scikit-learn

### Subtask:
Install the `scikit-learn` library, which provides the `train_test_split` function essential for this task. This is necessary if it's not already installed in the environment.

**Reasoning**:
To install the `scikit-learn` library, I will use the `pip install` command in a code cell.

In [43]:
get_ipython().system('pip install scikit-learn')

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

**Reasoning**:
Now that scikit-learn is confirmed to be installed, I will define the `perform_train_test_split` function as described in the task, which will use `train_test_split` with stratification on `MatchGroupId`.

In [44]:
from sklearn.model_selection import train_test_split

def perform_train_test_split(df, train_test_ratio=0.7):
    """
    Splits the input DataFrame into training and testing sets,
    stratifying by 'MatchGroupId'.

    Args:
        df (pd.DataFrame): The input DataFrame.
        train_test_ratio (float): The ratio of the training set size to the full dataset size.

    Returns:
        tuple: A tuple containing the training and testing DataFrames.
    """
    train_df, test_df = train_test_split(df,
                                         train_size=train_test_ratio,
                                         random_state=42,
                                         stratify=df['MatchGroupId'])
    return train_df, test_df

print("Defined perform_train_test_split function.")

Defined perform_train_test_split function.

**Reasoning**:
Now I will apply the `perform_train_test_split` function to the main dataframe `df` with a `train_test_ratio` of 0.7, and then print the shapes of the resulting `train_df` and `test_df` to verify the split.

In [45]:
train_df, test_df = perform_train_test_split(df, train_test_ratio=0.7)

print(f"Shape of train_df: {train_df.shape}")
print(f"Shape of test_df: {test_df.shape}")

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

**Reasoning**:
The previous code failed because some `MatchGroupId` values only appeared once, preventing stratified splitting. To fix this, I will modify the `perform_train_test_split` function to first identify and separate `MatchGroupId`s with single occurrences. These single-occurrence groups will then be added to the training set after performing a stratified split on the remaining data, ensuring all data is included and the stratification works for valid groups.

In [46]:
from sklearn.model_selection import train_test_split
import numpy as np

def perform_train_test_split(df, train_test_ratio=0.7):
    """
    Splits the input DataFrame into training and testing sets,
    stratifying by 'MatchGroupId' where possible.

    Args:
        df (pd.DataFrame): The input DataFrame.
        train_test_ratio (float): The ratio of the training set size to the full dataset size.

    Returns:
        tuple: A tuple containing the training and testing DataFrames.
    """
    # Identify MatchGroupId counts
    matchgroup_counts = df['MatchGroupId'].value_counts()

    # Identify MatchGroupIds that appear only once
    single_occurrence_matchgroupids = matchgroup_counts[matchgroup_counts == 1].index

    # Separate DataFrame into stratifiable and non-stratifiable parts
    df_stratifiable = df[~df['MatchGroupId'].isin(single_occurrence_matchgroupids)]
    df_non_stratifiable = df[df['MatchGroupId'].isin(single_occurrence_matchgroupids)]

    # Perform stratified split on the stratifiable part
    if not df_stratifiable.empty:
        train_df_stratified, test_df_stratified = train_test_split(df_stratifiable,
                                                                     train_size=train_test_ratio,
                                                                     random_state=42,
                                                                     stratify=df_stratifiable['MatchGroupId'])
    else:
        train_df_stratified = pd.DataFrame(columns=df.columns)
        test_df_stratified = pd.DataFrame(columns=df.columns)

    # Add non-stratifiable rows to the training set to avoid data loss
    train_df = pd.concat([train_df_stratified, df_non_stratifiable], ignore_index=True)
    test_df = test_df_stratified

    # If the total number of samples is small and test_size becomes 0 for stratified split
    # or if some strata end up in only one set due to very small counts (e.g., 2 samples in a strata)
    # It's better to ensure a minimum test set size if possible
    # However, given the current data, this approach should work.

    return train_df, test_df

# Re-run the split with the modified function
train_df, test_df = perform_train_test_split(df, train_test_ratio=0.7)

print(f"Shape of train_df: {train_df.shape}")
print(f

SyntaxError: incomplete input (ipython-input-220214923.py, line 51)

**Reasoning**:
The previous code block resulted in a `SyntaxError` due to an incomplete `print` statement. I need to complete the f-string for printing the shape of `test_df` to fix this syntax error.

In [47]:
from sklearn.model_selection import train_test_split
import numpy as np

def perform_train_test_split(df, train_test_ratio=0.7):
    """
    Splits the input DataFrame into training and testing sets,
    stratifying by 'MatchGroupId' where possible.

    Args:
        df (pd.DataFrame): The input DataFrame.
        train_test_ratio (float): The ratio of the training set size to the full dataset size.

    Returns:
        tuple: A tuple containing the training and testing DataFrames.
    """
    # Identify MatchGroupId counts
    matchgroup_counts = df['MatchGroupId'].value_counts()

    # Identify MatchGroupIds that appear only once
    single_occurrence_matchgroupids = matchgroup_counts[matchgroup_counts == 1].index

    # Separate DataFrame into stratifiable and non-stratifiable parts
    df_stratifiable = df[~df['MatchGroupId'].isin(single_occurrence_matchgroupids)]
    df_non_stratifiable = df[df['MatchGroupId'].isin(single_occurrence_matchgroupids)]

    # Perform stratified split on the stratifiable part
    if not df_stratifiable.empty:
        train_df_stratified, test_df_stratified = train_test_split(df_stratifiable,
                                                                     train_size=train_test_ratio,
                                                                     random_state=42,
                                                                     stratify=df_stratifiable['MatchGroupId'])
    else:
        train_df_stratified = pd.DataFrame(columns=df.columns)
        test_df_stratified = pd.DataFrame(columns=df.columns)

    # Add non-stratifiable rows to the training set to avoid data loss
    train_df = pd.concat([train_df_stratified, df_non_stratifiable], ignore_index=True)
    test_df = test_df_stratified

    # If the total number of samples is small and test_size becomes 0 for stratified split
    # or if some strata end up in only one set due to very small counts (e.g., 2 samples in a strata)
    # It's better to ensure a minimum test set size if possible
    # However, given the current data, this approach should work.

    return train_df, test_df

# Re-run the split with the modified function
train_df, test_df = perform_train_test_split(df, train_test_ratio=0.7)

print(f"Shape of train_df: {train_df.shape}")
print(f"Shape of test_df: {test_df.shape}")

Shape of train_df: (3, 27)
Shape of test_df: (2, 27)

**Reasoning**:
The previous steps successfully split the data. Now, to verify the stratification, I will calculate and display the distribution of `MatchGroupId` sizes for the original DataFrame `df`, and the newly created `train_df` and `test_df`.

In [48]:
print("MatchGroupId distribution in original df:")
print(df['MatchGroupId'].value_counts())
print("\nMatchGroupId distribution in train_df:")
print(train_df['MatchGroupId'].value_counts())
print("\nMatchGroupId distribution in test_df:")
print(test_df['MatchGroupId'].value_counts())

MatchGroupId distribution in original df:
MatchGroupId
14443554    2
14443555    2
14443553    1
Name: count, dtype: int64

MatchGroupId distribution in train_df:
MatchGroupId
14443555    1
14443554    1
14443553    1
Name: count, dtype: int64

MatchGroupId distribution in test_df:
MatchGroupId
14443555    1
14443554    1
Name: count, dtype: int64

## Final Task

### Subtask:
Provide a summary of the implemented stratified train-test split function and confirm its successful application and verification.

## Summary:

### Data Analysis Key Findings
*   The `scikit-learn` library was already installed in the environment.
*   An initial attempt to perform a stratified train-test split directly on `MatchGroupId` failed due to a `ValueError`, as some `MatchGroupId`s had only one member, which is insufficient for stratification.
*   The `perform_train_test_split` function was refined to handle this edge case by separating `MatchGroupId`s with single occurrences, performing stratified splitting on the remaining data, and then adding the single-occurrence `MatchGroupId`s entirely to the training set to prevent data loss.
*   After the successful application of the revised function, the `train_df` resulted in a shape of (3, 27) and the `test_df` in a shape of (2, 27).
*   The original DataFrame `df` contained `MatchGroupId`s with counts of 2, 2, and 1. Post-split, `train_df` contained `MatchGroupId`s with counts of 1, 1, and 1, while `test_df` contained `MatchGroupId`s with counts of 1 and 1. This confirms that the single-occurrence `MatchGroupId` was placed entirely in the training set, and the other groups were split as evenly as possible.

### Insights or Next Steps
*   The implemented stratified train-test split function effectively addresses the challenge of `MatchGroupId`s with single occurrences by ensuring they are included in the training set, thus maintaining data integrity while still stratifying the rest of the dataset.
*   While the current approach handles single-occurrence groups, for extremely small datasets or very granular stratification keys, it's important to monitor whether all strata maintain a representative distribution in both train and test sets. Further analysis could explore techniques for handling very small strata (e.g., merging them) if maintaining perfect proportionality becomes critical.